spring:
  application:
    name: shop
  h2:
    console:
      enabled: true
  datasource:
    datasource-type:
      default:
        reader:
          url: jdbc:h2:mem:testdb
          username: sa
          hikari:
            minimum-idle: 10
            maximum-pool-size: 10
        writer:
          url: jdbc:h2:mem:testdb
          username: sa
          hikari:
            minimum-idle: 5
            maximum-pool-size: 5
      yamsroun:
        writer:
          url: jdbc:h2:mem:testdb
          username: sa
          hikari:
            minimum-idle: 10
            maximum-pool-size: 10
  task:
    scheduling:
      pool:
        size: 5
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}][%X{userId:-}][%X{userIp:-}]"
  level:
    com.megazone.springbootboilerplate: debug
  #    root: info
  #    com.megazone.com.megazone.springbootboilerplate.feign: debug
  #    org:
  #      springframework:
  #        web: info
  #    jdbc:
  #      sqlonly: off
  #      sqltiming: debug
  #      resultsettable: debug
  #      audit: off
  #      resultset: off
  #      connection: off

# 사용할 actuator endpoint 설정
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  tracing:
    sampling:
      probability: 1.0 # 모든 tracing 기록
  server:
    port: 8081

#  # prometheus http_server_requests_seconds_bucket metric 활성화
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true

#   # file logging
#  file:
#    name: logs/application.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: logs/application-%d{yyyyMMdd}.%i.log
#      max-history: 5

feign:
  backoffice:
    base-url: http://bo.mz.com

scheduler:
  enabled: true
  groups:
    a:
      enabled: true
    b:
      enabled: false
