spring:
  application:
    name: shop
  h2:
    console:
      enabled: true
  datasource:
    datasourcePair:
      default:
        reader:
          url: jdbc:h2:mem:testdb
          username: sa
        writer:
          url: jdbc:h2:mem:testdb
          username: sa

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}][%X{userId:-}][%X{userIp:-}]"
  level:
    com.megazone.springbootboilerplate: debug
  #    root: info
  #    com.megazone.com.megazone.springbootboilerplate.feign: debug
  #    org:
  #      springframework:
  #        web: info
  #    jdbc:
  #      sqlonly: off
  #      sqltiming: debug
  #      resultsettable: debug
  #      audit: off
  #      resultset: off
  #      connection: off


#   # file logging
#  file:
#    name: logs/application.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: logs/application-%d{yyyyMMdd}.%i.log
#      max-history: 5
