server:
  shutdown: graceful

spring:
  profiles.active: local
  application:
    name: shop
  base-package: com.megazone.springbootboilerplate

  lifecycle.timeout-per-shutdown-phase: 1m

  datasource:
    reader:
      url: jdbc:log4jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: root
      password: 1234
    writer:
      url: jdbc:log4jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: root
      password: 1234
      hikari:
        minimum-idle: 10
        maximum-pool-size: 10

    hikari:
      minimum-idle: 20
      maximum-pool-size: 20
      connection-timeout: 2700
      validation-timeout: 2100
      leak-detection-threshold: 59000
      max-lifetime: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true  #saveAll ?? ??

mybatis:
  base-package: ${spring.base-package}.*.infrastructure.provider.mybatis
  type-handlers-packages:
    - ${mybatis.base-package}.typehandler
  type-aliases-packages:
    - ${spring.base-package}.*.domain
    - ${spring.base-package}.*.application.dto.response.query

logging:
  level:
    jdbc:
      sqlonly: debug
      sqltiming: debug
      resultsettable: debug
      audit: off
      resultset: off
      connection: off