### 토큰 정보 확인
GET localhost:8080/members/me
Authorization: Bearer {{accessToken}}

### 토큰 정보 확인
GET localhost:8080/members/admin
Authorization: Bearer {{accessToken}}



### 회원 가입
POST localhost:8080/members
Content-Type: application/json

{
  "id": "sam@gmail.com",
  "password": "abcd",
  "name": "sam",
  "roles": "MEMBER"
}



### 멤버 토큰 요청 (로그인)
POST localhost:8080/login

{
  "type": "token",
  "id": "sam@gmail.com",
  "password": "abcd"
}

### 어드민 토큰 요청 (로그인)
POST localhost:8080/login

{
  "type": "token",
  "id": "gilbert@gmail.com",
  "password": "123456"
}



### 리프레시 토큰 요청 (로그인)
POST localhost:8080/login

{
  "type": "refresh",
  "refreshToken": "{{refreshToken}}"
}
